# Generated by Django 5.2.17 on 2026-09-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_message_delete_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="massage",
            new_name="message",
        ),
    ]
