# Generated by Django 5.2.17 on 2026-09-30 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_rename_massage_message_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
