# Generated by Django 5.2.17 on 2026-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_message_created_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_date"]},
        ),
    ]
