# Generated by Django 5.2.17 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
