# Generated by Django 5.2.17 on 2026-09-30 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_person_age_person_email_alter_person_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
