# Generated by Django 5.2.17 on 2026-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_person_created_date_person_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
