# Generated by Django 5.2.17 on 2026-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_date"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="status",
            new_name="upload_now",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
